In [36]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [37]:
#Read data
data = pd.read_excel('data.xlsx', sheet_name='PS19A_PERSON__SmplR10K')

#Shape the data
data.shape

(999, 31)

In [38]:
#Brief overview of 5 rows
data.head(1)

person_id    person_name  \
0      89830  Hata, Yoshiki   

                                      person_address  \
0  c/o Hitachi Appliances, Inc. 390 Muramatsu, Sh...   

                                                cln1  cln2  cln3  \
0  c/o Hitachi Appliances Inc. 390 Muramatsu Shim...   NaN   NaN   

  person_ctry_code  cnt  chr_len  chr_len_label  ...  street   nr  \
0               JP    1       90              1  ...     NaN  NaN   

           area    postal                       city     region  country  \
0  Shizuoka-ken  424-0926   Shizuoka-shi, Shimizu-ku  Muramatsu      NaN   

   unclear status label  
0      NaN    NaN     0  

[1 rows x 31 columns]

In [39]:
#Fill all empty values with 0 for feature columns
data['person_name'] = data['person_name'].fillna(0)
data['person_address'] = data['person_address'].fillna(0)
data['person_ctry_code'] = data['person_ctry_code'].fillna(0)

#Fill all empty values with 0 for predicted columns
data['country'] = data['country'].fillna(0)
data['city'] = data['city'].fillna(0)
data['region'] = data['region'].fillna(0)
data['postal'] = data['postal'].fillna(0)
data['area'] = data['area'].fillna(0)
data['street'] = data['street'].fillna(0)
data['co'] = data['co'].fillna(0)
data['building'] = data['building'].fillna(0)
data['nr'] = data['nr'].fillna(0)

In [40]:
#Brief overview of first 5 rows
data.head(5)

person_id                                       person_name  \
0      89830                                     Hata, Yoshiki   
1     118819   Sakamura, Ken, Intellectual Property Department   
2     227620        Takeda, Yuji Yokkaichi Plant of Mitsubishi   
3     300146  INOUE, Mitsuo, MITSUBISHI DENKI KABUSHIKI KAISHA   
4     433394                  The Engineering Business Limited   

                                      person_address  \
0  c/o Hitachi Appliances, Inc. 390 Muramatsu, Sh...   
1  NTT DoCoMo, Inc., Sanno Park Tower, 11-1, Naga...   
2  Gas Chemical Company, Inc., 4-16-2, Hinagahiga...   
3  2-3, Marunouchi 2-chome, Chiyoda-ku,Tokyo 100-...   
4  Broomhaugh House Riding Mill,Northumberland NE...   

                                                cln1  cln2  cln3  \
0  c/o Hitachi Appliances Inc. 390 Muramatsu Shim...   NaN   NaN   
1  NTT DoCoMo Inc. Sanno Park Tower 11-1 Nagata- ...   NaN   NaN   
2  Gas Chemical Company Inc. 4-16-2 Hinagahigashi...   NaN   NaN   
3   2-3 Marunouchi 2-chome Chiyoda-ku Tokyo 100-8310   NaN   NaN   
4  Broomhaugh House Riding Mill Northumberland NE...   NaN   NaN   

  person_ctry_code  cnt  chr_len  chr_len_label  ...  street   nr  \
0               JP    1       90              1  ...       0    0   
1               JP    1       89              1  ...       0    0   
2               JP    1       76              1  ...       0    0   
3               JP    1       50              1  ...       0  2-3   
4               GB    1       52              1  ...       0    0   

            area    postal                       city          region  \
0   Shizuoka-ken  424-0926   Shizuoka-shi, Shimizu-ku       Muramatsu   
1        nagata-  100-6150                      Tokyo               0   
2  Hinagahigashi         0              Yokkaichi-shi        510-0886   
3     Chiyoda-ku  100-8310                      Tokyo               0   
4              0  NE44 6EG                Riding Mill  Northumberland   

   country  unclear status label  
0        0      NaN    NaN     0  
1        0      NaN    NaN     0  
2        0      NaN    NaN     0  
3        0      NaN    NaN     0  
4        0      NaN    NaN     0  

[5 rows x 31 columns]

In [41]:
from sklearn.preprocessing import LabelEncoder
l3 = LabelEncoder()

person_name = data.person_name.values
person_name = l3.fit_transform(person_name)

person_address = data["person_address"].values.astype(str)
person_address = l3.fit_transform(person_address)

person_ctry_code = data.person_ctry_code.values
person_ctry_code = l3.fit_transform(person_ctry_code)

#Make the columns as string and encode it to a numeric
country = data.country.values.astype(str)
country = l3.fit_transform(country)

region = data.region.values.astype(str)
region = l3.fit_transform(region)

city = data.city.values.astype(str)
city = l3.fit_transform(city)

postal = data.postal.values.astype(str)
postal = l3.fit_transform(postal)

area = data.country.values.astype(str)
area = l3.fit_transform(area)

nr = data.nr.values.astype(str)
nr = l3.fit_transform(nr)

street = data.street.values.astype(str)
street = l3.fit_transform(street)

building = data.building.values.astype(str)
building = l3.fit_transform(building)

co = data.co.values.astype(str)
co = l3.fit_transform(co)


In [42]:
data['person_name'] = person_name
data['person_address'] = person_address
data['person_ctry_code'] = person_ctry_code

#Replace originalcolumns witht the numeric columns
data['country'] = country
data['region'] = region
data['city'] = city
data['postal'] = postal
data['area'] = area
data['nr'] = nr
data['street'] = street
data['building'] = building
data['co'] = co


In [43]:
#Brief overview of first 5
data.head(5)

person_id  person_name  person_address  \
0      89830          302             896   
1     118819          763             630   
2     227620          849             442   
3     300146          338             102   
4     433394          862             330   

                                                cln1  cln2  cln3  \
0  c/o Hitachi Appliances Inc. 390 Muramatsu Shim...   NaN   NaN   
1  NTT DoCoMo Inc. Sanno Park Tower 11-1 Nagata- ...   NaN   NaN   
2  Gas Chemical Company Inc. 4-16-2 Hinagahigashi...   NaN   NaN   
3   2-3 Marunouchi 2-chome Chiyoda-ku Tokyo 100-8310   NaN   NaN   
4  Broomhaugh House Riding Mill Northumberland NE...   NaN   NaN   

   person_ctry_code  cnt  chr_len  chr_len_label  ...  street  nr  area  \
0                23    1       90              1  ...      18   3     1   
1                23    1       89              1  ...      18   3     1   
2                23    1       76              1  ...      18   3     1   
3                23    1       50              1  ...      18  92     1   
4                15    1       52              1  ...      18   3     1   

   postal  city  region  country  unclear status  label  
0     151     1      91        1      NaN    NaN      0  
1      30   606       3        1      NaN    NaN      0  
2       5   668       4        1      NaN    NaN      0  
3      32   606       3        1      NaN    NaN      0  
4     405   506     107        1      NaN    NaN      0  

[5 rows x 31 columns]

In [44]:
#Detailed overview
data.describe()

person_id  person_name  person_address  cln2  cln3  \
count  9.990000e+02   999.000000      999.000000   0.0   0.0   
mean   2.070643e+07   499.000000      480.619620   NaN   NaN   
std    2.175683e+07   288.530761      271.033485   NaN   NaN   
min    3.540000e+03     0.000000        0.000000   NaN   NaN   
25%    3.854371e+06   249.500000      248.500000   NaN   NaN   
50%    9.143170e+06   499.000000      488.000000   NaN   NaN   
75%    4.806491e+07   748.500000      718.500000   NaN   NaN   
max    6.971232e+07   998.000000      942.000000   NaN   NaN   

       person_ctry_code    cnt     chr_len  chr_len_label     nbr_tok  ...  \
count        999.000000  999.0  999.000000          999.0  999.000000  ...   
mean          26.045045    1.0   32.092092            1.0    4.703704  ...   
std           13.166384    0.0   26.633592            0.0    3.758530  ...   
min            0.000000    1.0    2.000000            1.0    1.000000  ...   
25%           14.000000    1.0   10.000000            1.0    1.000000  ...   
50%           23.000000    1.0   29.000000            1.0    4.000000  ...   
75%           41.000000    1.0   47.000000            1.0    7.000000  ...   
max           42.000000    1.0  164.000000            1.0   20.000000  ...   

         building      street          nr        area      postal        city  \
count  999.000000  999.000000  999.000000  999.000000  999.000000  999.000000   
mean     8.287287  117.695696   49.288288    1.436436   92.729730  311.948949   
std     12.921086  140.093289   75.903938    2.545323  127.941906  221.292538   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      5.000000   18.000000    3.000000    1.000000    5.000000  100.500000   
50%      5.000000   18.000000    3.000000    1.000000    5.000000  315.000000   
75%      5.000000  216.500000   81.000000    1.000000  174.500000  519.500000   
max     85.000000  461.000000  266.000000   23.000000  418.000000  687.000000   

           region     country  status       label  
count  999.000000  999.000000     0.0  999.000000  
mean    31.118118    1.436436     NaN    0.470470  
std     46.385399    2.545323     NaN    0.499377  
min      0.000000    0.000000     NaN    0.000000  
25%      3.000000    1.000000     NaN    0.000000  
50%      3.000000    1.000000     NaN    0.000000  
75%     48.000000    1.000000     NaN    1.000000  
max    165.000000   23.000000     NaN    1.000000  

[8 rows x 28 columns]

In [45]:
from sklearn.model_selection import train_test_split

#List columns to predict and input columns
predicted_class = ['co', 'building', 'street', 'nr', 'area', 'postal', 'city', 'region', 'country']
feature_columns = ['person_name', 'person_address', 'person_ctry_code']

In [46]:
#Gather input data and data to predict
X = data[feature_columns].values
Y = data[predicted_class].values

#Create training and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3) #70% training and 30% test

In [47]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [48]:
#from sklearn import metrics
#Model Accuracy, how often is the classifier correct?
#print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

In [49]:
print(y_pred)

[[ 1  5 18 ...  2  3  1]
 [ 1  5 18 ... 36  3  1]
 [ 1  5 18 ...  2  3  1]
 ...
 [ 1  5 18 ...  2  3  1]
 [ 1  5 18 ...  2  3  1]
 [ 1  5 18 ...  2  3  1]]
